### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /root/LLMs/Qwen2___5-7B-Instruct/
adapter_name_or_path: saves/sft_lora
template: qwen
trust_remote_code: true

### export
export_dir: output/merge_lora
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
